### PR TITLE
overload _alg_autodiff

### PR DESCRIPTION
**Pull request by vpuri3**
fix downstream errors in https://github.com/SciML/OrdinaryDiffEq.jl/pull/1917

### CODE REVIEW

**Comment by vpuri3** [comment]
all tests passed locally with https://github.com/SciML/OrdinaryDiffEq.jl/pull/1917 branch

**Comment by vpuri3** [comment]
@gaurav-arya can you review

**Comment by vpuri3** [comment]
@ChrisRackauckas @nathanaelbosch , could you approve workflow please? This should be good to go now that OrdinaryDiffEq. 6.5.2 has released

**Comment by nathanaelbosch** [comment]
Thanks a lot!

**Pull request merged**
