### PR TITLE
Overload `OrdinaryDiffEq.get_fsalfirstlast` to fix installation issues

### PR DESCRIPTION
**Pull request by nathanaelbosch**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
wait, didn't I give a PR for this?

**Comment by ChrisRackauckas** [comment]
Sorry, I had the branch already but forgot to open https://github.com/nathanaelbosch/ProbNumDiffEq.jl/pull/326

**Comment by nathanaelbosch** [comment]
Closed in favor of #326

**Comment by nathanaelbosch** [comment]
Closed in favor of #326

**Pull request closed without merging**
