### PR TITLE
Made the state-initialization a bit easier

### PR DESCRIPTION
**Pull request by nathanaelbosch**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
BTW you might want to re-benchmark against OrdinaryDiffEq since it had a few performance regression fixes. You might want to make use of https://github.com/YingboMa/FastBroadcast.jl internally as well.

**Comment by nathanaelbosch** [comment]
Thanks for letting me know! I should indeed do a proper benchmark soon. I'll also have a look at FastBroadcast.jl, I just need to find out where and how to best use it since we have a lot of matrix-matrix and matrix-vector multiplications in here. But thanks for the pointing me to it!

**Comment by ChrisRackauckas** [comment]
Oh yes, you should look into https://github.com/JuliaLinearAlgebra/Octavian.jl for those if they are small-ish.

**Comment by nathanaelbosch** [comment]
Wow, thanks again for that recommendation, never heard of Octavian.jl before. I'm still struggling to find the right balance between functional, generic code, and optimizing internal solver operations, since as you said many things depend on the actual problem size, number types, etc. Anyways, I think next month I'll do some refactoring and look a bit more into code optimizations again.

**Pull request merged**
